name: Sync whitelist

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download external file
        run: |
          echo "Загружаем файл..."
          curl -fsSL https://raw.githubusercontent.com/zieng2/wl/main/vless_lite.txt -o external.txt || {
            echo "Ошибка загрузки"
            exit 1
          }

          if [ ! -s external.txt ]; then
            echo "Загруженный файл пуст"
            exit 1
          fi

      - name: Merge with metadata
        run: |
          COUNT=$(grep -cve '^\s*$' external.txt)
          DATE=$(date -u "+%Y-%m-%d %H:%M:%S")

          {
            cat header
            echo "#auto-selected-at: $DATE"
            echo "#servers-count: $COUNT"
            echo ""
            cat external.txt
          } > combined.txt

      - name: Update file if changed
        run: |
          if ! cmp -s combined.txt wl; then
            mv combined.txt wl
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            rm combined.txt
          fi

      - name: Commit changes
        if: env.CHANGED == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add wl
          git commit -m "auto: update merged list"
          git push
